### ISSUE TITLE
Code fix provider to move invalid single field regions into existing regions as fields

### ISSUE THREAD

**Issue by mikaellindemann** [PiranhaCMS/piranha.core.analyzers#1]
The current solution offers to create a new complex region as a nested class.

Another option could be to move the invalid single field region into an existing complex region for the content class.

Note that this has the additional complexity of potentially modifying multiple documents in the solution.

**Comment by mikaellindemann** [comment]
@tidyui just as a side question regarding the one you answered in #9, would you also consider this an error?

**Comment by tidyui** [comment]
Yes! Moving an:

~~~ csharp
public class MyPage : Page<MyPage>
{
    [Region]
    public CheckBoxField MyCheck { get; set; }
}
~~~

into a class containing just one field will result in an error. The guidelines that the fields are not intended to be used as single field regions is more from an aesthetical point of view as it will not be rendered in an optimal way in the manager. From a technical point of view it's totally fine.
