### ISSUE TITLE
Build fails in Debug when Release hasn't been previously built

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core.analyzers#10]
The build tasks automatically tries to create NuGet-packages regardless of the build configuration. When building in Debug without have previously built in Release build fails as it can't find the release folder to package the NuGet-package from.

**Comment by mikaellindemann** [comment]
Good catch.
I was thinking about moving the nuspec properties into the csproj file, such that all usual variables are available without having to assign them only for availability in nuspec.
