### ISSUE TITLE
Detect usage of field settings attributes

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core.analyzers#16]
Hi there @mikaellindemann. In `9.0` we will be adding support for adding settings for fields, for example a `StringField` could have the following attribute.

~~~ csharp
[Field]
[StringFieldSettings(MaxLength = 32)]
public StringField Title { get; set; }
~~~

Each field type supporting settings will have it's own attribute with the applicable settings defined. My question here is if we can add support for the analyzers to check that the correct attribute is assigned to a property with the same property type, in other words so the develop doesn't do this.

~~~ csharp
[Field]
[StringFieldSettings(MaxLength = 32)]
public ImageField PrimaryImage { get; set; }
~~~

**Comment by mikaellindemann** [comment]
Of course!
Do StringFieldSettingsAttribute and StringField have anything in common except for the name/prefix?

One way is to make it a convention that a field type can only have a {field type name}SettingsAttribute attribute applied.
Otherwise we can build a list for the built-in fields with settings to avoid false positives.

**Comment by tidyui** [comment]
Unfortunately they share nothing but the name, and .NET does not provide any way to specify the property type in `AttributeUsageAttribute`. As a field property can (and always have) several attributes, at least one `FieldAttribute` and one settings attribute the check should probably be the other way around, that a `StringFieldSettingsAttribute` can only be applied to a property with the property type `StringField`. And yes, for developer simplicity I'm aiming for a one-to-one mapping with fields & attributes, although I can't promise at this point that **all** field types will have a matching settings attribute.

**Comment by mikaellindemann** [comment]
If I publish a prerelease package to NuGet, can you then verify the analyzer against a project?
Also, it doesn't provide a code fix currently, but that could be added in time.

**Comment by mikaellindemann** [comment]
@tidyui I have pushed a prerelease on NuGet https://www.nuget.org/packages/Piranha.Analyzers/9.0.0-alpha1

**Comment by mikaellindemann** [comment]
An updated package with this analyzer has been submitted to nuget.org: https://www.nuget.org/packages/Piranha.Analyzers/9.0.0.
Should become available shortly.
